// <auto-generated />
using System;
using ClaimSettlement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimSettlement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClaimSettlementDbContext))]
    partial class ClaimSettlementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.AdjusterAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjusterId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Rationale")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("SettlementOverride")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AdjusterId", "AssignedAt");

                    b.HasIndex("ClaimId", "AssignedAt");

                    b.ToTable("AdjusterAssignments");
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.AgentOutput", b =>
                {
                    b.Property<Guid>("OutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("OutputPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("OutputId");

                    b.HasIndex("ClaimId", "AgentId", "CreatedAt");

                    b.ToTable("AgentOutputs", t =>
                        {
                            t.HasCheckConstraint("CK_AgentOutput_OutputPayload_IsJson", "ISJSON([OutputPayload]) = 1");
                        });
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("EntryId");

                    b.HasIndex("ClaimId", "Timestamp");

                    b.HasIndex("ProviderId", "Timestamp");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_Payload_IsJson", "ISJSON([Payload]) = 1");
                        });
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClaimantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("DateOfLoss")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ClaimId");

                    b.HasIndex("ProviderId", "PolicyNumber", "DateOfLoss");

                    b.HasIndex("ProviderId", "Status", "CreatedAt");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.ClaimPipelineState", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentOutputs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedSteps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ClaimId");

                    b.HasIndex("ProviderId", "Status");

                    b.ToTable("ClaimPipelineStates", t =>
                        {
                            t.HasCheckConstraint("CK_ClaimPipelineState_AgentOutputs_IsJson", "ISJSON([AgentOutputs]) = 1");

                            t.HasCheckConstraint("CK_ClaimPipelineState_CompletedSteps_IsJson", "ISJSON([CompletedSteps]) = 1");
                        });
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.ProviderConfiguration", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("AdjusterSlaPeriodHours")
                        .HasColumnType("int");

                    b.Property<string>("AlwaysManualClaimTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimTypeMandatoryFields")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverageMappingRules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeduplicationWindowDays")
                        .HasColumnType("int");

                    b.Property<string>("ExclusionSets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InformationRequestDeadlineDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("ManualReviewClaimAmountThreshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ManualReviewFraudThreshold")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("PipelineConcurrencyLimit")
                        .HasColumnType("int");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SupportedClaimTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportedNotificationChannels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderId");

                    b.HasIndex("IsActive");

                    b.ToTable("ProviderConfigurations", t =>
                        {
                            t.HasCheckConstraint("CK_ProviderConfiguration_AlwaysManualClaimTypes_IsJson", "ISJSON([AlwaysManualClaimTypes]) = 1");

                            t.HasCheckConstraint("CK_ProviderConfiguration_ClaimTypeMandatoryFields_IsJson", "ISJSON([ClaimTypeMandatoryFields]) = 1");

                            t.HasCheckConstraint("CK_ProviderConfiguration_CoverageMappingRules_IsJson", "ISJSON([CoverageMappingRules]) = 1");

                            t.HasCheckConstraint("CK_ProviderConfiguration_ExclusionSets_IsJson", "ISJSON([ExclusionSets]) = 1");

                            t.HasCheckConstraint("CK_ProviderConfiguration_FraudThreshold_Range", "[ManualReviewFraudThreshold] >= 0.30 AND [ManualReviewFraudThreshold] <= 0.90");

                            t.HasCheckConstraint("CK_ProviderConfiguration_SupportedClaimTypes_IsJson", "ISJSON([SupportedClaimTypes]) = 1");

                            t.HasCheckConstraint("CK_ProviderConfiguration_SupportedNotificationChannels_IsJson", "ISJSON([SupportedNotificationChannels]) = 1");
                        });
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.AdjusterAssignment", b =>
                {
                    b.HasOne("ClaimSettlement.Domain.Entities.Claim", "Claim")
                        .WithMany("AdjusterAssignments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.AgentOutput", b =>
                {
                    b.HasOne("ClaimSettlement.Domain.Entities.Claim", "Claim")
                        .WithMany("AgentOutputs")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ClaimSettlement.Domain.Entities.Claim", "Claim")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.ClaimPipelineState", b =>
                {
                    b.HasOne("ClaimSettlement.Domain.Entities.Claim", "Claim")
                        .WithOne("PipelineState")
                        .HasForeignKey("ClaimSettlement.Domain.Entities.ClaimPipelineState", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimSettlement.Domain.Entities.Claim", b =>
                {
                    b.Navigation("AdjusterAssignments");

                    b.Navigation("AgentOutputs");

                    b.Navigation("AuditLogs");

                    b.Navigation("PipelineState");
                });
#pragma warning restore 612, 618
        }
    }
}
